# Generated by Django 6.0.7 on 2026-07-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fa-brands fa-python', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='technologies/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('topics_covered', models.TextField(blank=True, help_text='One topic per line')),
                ('experience', models.CharField(choices=[('fresher', 'Fresher (0-1 yrs)'), ('junior', 'Junior (1-3 yrs)'), ('mid', 'Mid (3-6 yrs)'), ('senior', 'Senior (6+ yrs)')], default='fresher', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('hindi', 'Hindi')], default='english', max_length=20)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.ImageField(upload_to='pdfs/thumbnails/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='pdfs/banners/')),
                ('preview_pdf', models.FileField(blank=True, help_text='A short free preview/sample shown to everyone', null=True, upload_to='pdfs/previews/')),
                ('original_pdf', models.FileField(help_text='The full, secure file only served through the protected download view', upload_to='pdfs/originals/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('seo_keywords', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='pdfs.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='pdfs.company')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='pdfs.technology')),
            ],
            options={
                'verbose_name': 'Interview PDF',
                'verbose_name_plural': 'Interview PDFs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='pdfs_interv_slug_d3ce7e_idx'), models.Index(fields=['is_published', 'is_featured'], name='pdfs_interv_is_publ_91286c_idx'), models.Index(fields=['is_published', 'is_trending'], name='pdfs_interv_is_publ_ae3900_idx')],
            },
        ),
    ]
