# Generated by Django 6.0.7 on 2026-07-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent for nested category groups such as Web Development > Frontend.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pdfs.category'),
        ),
        migrations.AddField(
            model_name='technology',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='technologies/banners/'),
        ),
        migrations.AddField(
            model_name='technology',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Every category where this technology should be displayed.', related_name='technologies', to='pdfs.category'),
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional primary category used for organization in Django Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_technologies', to='pdfs.category'),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='technology',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='technology',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
