# Generated by Django 6.0.7 on 2026-07-24 15:07

from django.db import migrations, models


def classify_existing_pdfs(apps, schema_editor):
    InterviewPDF = apps.get_model("pdfs", "InterviewPDF")
    InterviewPDF.objects.all().update(content_type="interview_questions")
    InterviewPDF.objects.filter(is_published=True).update(status="published")
    InterviewPDF.objects.filter(is_published=False).update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0005_remove_legacy_category_technology_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewpdf',
            options={'ordering': ['category', 'technology', 'content_type', 'display_order', 'title'], 'verbose_name': 'Interview PDF', 'verbose_name_plural': 'Interview PDFs'},
        ),
        migrations.RemoveConstraint(
            model_name='interviewpdf',
            name='pdfs_interview_unique_category_display_order',
        ),
        migrations.AddField(
            model_name='interviewpdf',
            name='content_type',
            field=models.CharField(choices=[('interview_questions', 'Interview Questions'), ('notes', 'Notes'), ('cheat_sheet', 'Cheat Sheet'), ('projects', 'Projects'), ('mcqs', 'MCQs'), ('roadmap', 'Roadmap'), ('company_questions', 'Company Questions'), ('interview_experience', 'Interview Experience'), ('tutorial', 'Tutorial'), ('ebook', 'Ebook'), ('other', 'Other')], db_index=True, default='interview_questions', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewpdf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=12),
        ),
        migrations.RunPython(classify_existing_pdfs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='interviewpdf',
            constraint=models.UniqueConstraint(fields=('category', 'technology', 'content_type', 'title'), name='pdfs_content_unique_category_technology_type_title'),
        ),
    ]
