# Generated by Django 6.0.7 on 2026-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0006_alter_interviewpdf_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interviewpdf',
            index=models.Index(fields=['technology', 'status', 'content_type', 'display_order'], name='pdfs_tech_content_order_idx'),
        ),
    ]
